POST http://localhost:3001/api/patients/d27736ec-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

# {
#         "date": "2020-06-20",
#         "type": "Hospital",
#         "specialist": "Micheal Jackson",
#         "diagnosisCodes": ["M24.2","M51.2"],
#         "description":"Headache for two weeks.Probably will be fine soon",
#         "discharge": {
#           "date": "2020-10-16",
#           "criteria": "Back to normal."
#         }
# }
{
        "date": "2020-06-20",
        "type": "HealthCheck",
        "specialist": "Micheal Jackson",
        "diagnosisCodes": ["M24.2","M51.2"],
        "description":"Headache for two weeks.Probably will be fine soon",
        "HealthCheckRating":"HighRisk" 
}
  
